name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: main

      - name: Run dartfmt
        run: dart format --set-exit-if-changed .

  analzye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: main

      - name: Install dependencies
        run: dart pub get

      - name: Run dartanalyzer
        run: dart analyze --fatal-infos --fatal-warnings .

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Meson
        run: pip3 install meson

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Check Meson is available on PATH
        run: meson --version

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: main

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
